version: "3.1"

services:
  redis:
    container_name: redis
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - cargo_auction

networks:
  cargo_auction:
    external: true
