version: "3.1"

services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - cargo_auction

networks:
  cargo_auction:
    external: true
